name: .NET

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: list
      run: ls C4Bank.Deposit/bin
    - uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
         
  test:
    runs-on: ubuntu-latest
    needs: [build]    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: LS
      run: ls C4Bank.Deposit
    - uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - run: ls
    - run: ls C4Bank.Deposit/
    - name: Test
      run: dotnet test --no-build
