name: c4bank-application

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
         
  test:
    runs-on: ubuntu-latest
    needs: [build]    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Test
      run: dotnet test --no-build -v n
  
  c4sharp:
    runs-on: ubuntu-latest
    needs: [build]    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Instal c4scli
      run: dotnet tool install -g c4scli --version 1.1.152-beta
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Generate c4s artifacts
      run: c4scli build -o assets
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'c4s-assets-${{ github.run_id }}'
        path: assets
